"use client";

import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";

const FAQ_ITEMS = [
  {
    id: "what-is",
    question: "What is Trading Caller?",
    answer:
      "Trading Caller is an AI-powered trading companion for Solana. It generates LONG and SHORT signals using real technical analysis \u2014 RSI, MACD, support/resistance, and volume data \u2014 then tracks every call against actual market outcomes.",
  },
  {
    id: "how-generated",
    question: "How are signals generated?",
    answer:
      "Signals are generated by fetching real OHLCV data, calculating 14-period RSI, identifying support/resistance levels, checking MACD and momentum, and scoring confidence based on indicator confluence. No guessing, no vibes.",
  },
  {
    id: "performance",
    question: "How is performance tracked?",
    answer:
      "Every signal is tracked at 24h, 48h, and 7d intervals against real price data. We calculate win rate, PnL, profit factor, and outcome distribution (TP1/TP2/TP3 hits, stopped out, expired). All visible on the dashboard.",
  },
  {
    id: "financial-advice",
    question: "Is this financial advice?",
    answer:
      "No. Trading Caller provides AI-generated technical analysis signals for educational and informational purposes. Always do your own research and never trade more than you can afford to lose.",
  },
];

export function FaqSection() {
  return (
    <section className="py-20">
      <div className="flex flex-col gap-12 md:flex-row md:gap-16">
        {/* Left heading */}
        <div className="md:w-[30%]">
          <h2 className="text-3xl font-bold text-primary md:text-4xl">FAQs</h2>
        </div>

        {/* Right accordion */}
        <div className="md:w-[70%]">
          <Accordion>
            {FAQ_ITEMS.map(({ id, question, answer }) => (
              <AccordionItem key={id} id={id}>
                <AccordionTrigger id={id}>{question}</AccordionTrigger>
                <AccordionContent id={id}>{answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
